name: Build and push nightly

on:
  pull_request:
    branches: [ "master" ]


jobs:

  build-and-push-qwc2-minimal-nightly:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push rgdz-thalwil-webgis
        uses: docker/build-push-action@v3
        with:
          context: ./
          # do not push for the moment, to avoid load
          # push: true
          tags: ghcr.io/${{ github.repository }}:${{ github.head_ref }}-${{ github.sha }}
          target: prod
