name: Build and push latest

on:
  push:
    branches: [ "master" ]


jobs:

  build-and-rgdz-thalwil-webgis-latest:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push rgdz-thalwil-webgis
      uses: docker/build-push-action@v3
      with:
        context: ./
        push: true
        tags: ghcr.io/${{ github.repository }}:latest
        target: prod
